# For local development only - NOT PRODUCTION.
version: '3'

services:
  db:
    image: tinkerpop/gremlin-server
    command: conf/gremlin-rest-server-rest-modern.yaml
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8182" ]
      interval: 30s
      timeout: 10s
      retries: 5
  server:
    build: app
    depends_on:
      db:
        condition: service_healthy
    environment:
      ORBITAL_DB_ADDRESS: http://db:8182
    ports:
      - 5000:5000
    command: go test ./connectors/... .
