# For local development only - NOT PRODUCTION.
version: '3'

services:
  db:
    image: tinkerpop/gremlin-server
    command: conf/gremlin-server-rest-modern.yaml
  server:
    build: app
    environment:
      ORBITAL_DB_ADDRESS: http://db:8182
    ports:
    - 5000:5000
