database:
  type: gremlin
  endpoint: http://127.0.0.1:8182
service:
  port: 5000
lakes:
  - provider: aws
    store: athena
    address: db=default&region=us-west-2&output_location=s3://manta-innovations.queries
