name: Versioned Release Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  gh-release:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Release Pipeline
    steps:
      - uses: actions/checkout@v2

      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          tag_name: {{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true

  docker-release:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Docker Release Pipeline
    steps:
      - uses: actions/checkout@v2

      - name: Publish Docker image
        uses: docker/build-push-action@v2.5.0
        with:
          path: app
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
          repository: ${{ github.repository_owner }}/orbital
          registry: ghcr.io
          tags: ${{ github.ref }}
