name: Release Pipeline

on:
  push:
    branches: "main"

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Publish Docker image
        working-directory: app
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
          repository: jhole89/orbital
          registry: ghcr.io
          tags: latest
