name: Release Pipeline

on:
  push:
    branches: "main"

jobs:
  metrics-publish:
    runs-on: ubuntu-latest
    name: Metrics Pipeline
    steps:
      - uses: actions/checkout@v2

      - name: Publish GoCardReport
        uses: creekorful/goreportcard-action@v1

  docker-publish:
    runs-on: ubuntu-latest
    name: Docker Release Pipeline
    steps:
      - uses: actions/checkout@v2

      - name: Publish Docker image
        uses: docker/build-push-action@v1
        with:
          path: app
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
          repository: jhole89/orbital
          registry: ghcr.io
          tags: latest
